# Generated by Django 2.0 on 2020-12-04 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapters', models.CharField(max_length=30, verbose_name='小说章节')),
                ('text', models.TextField(verbose_name='章节内容')),
            ],
            options={
                'verbose_name_plural': '小说章节信息',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_name', models.CharField(max_length=30, verbose_name='书名')),
                ('book_author', models.CharField(max_length=30, verbose_name='作者')),
                ('book_num', models.IntegerField(primary_key=True, serialize=False, verbose_name='编号')),
                ('book_info', models.TextField(verbose_name='小说简介')),
                ('book_type', models.CharField(choices=[('1', '玄幻修真'), ('2', '仙侠武侠'), ('3', '历史军事'), ('4', '科幻游戏'), ('5', '悬疑灵幻'), ('6', '二次元'), ('7', '短篇小说')], max_length=10, verbose_name='小说类型')),
                ('book_hot', models.IntegerField(default=0, verbose_name='小说热度')),
                ('book_end', models.CharField(choices=[('1', '未完结'), ('2', '完结')], max_length=6, verbose_name='是否完结')),
                ('book_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='小说图片')),
            ],
            options={
                'verbose_name_plural': '小说信息',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_master', models.CharField(max_length=20, verbose_name='评论用户')),
                ('comment_text', models.TextField(verbose_name='评论内容')),
                ('comment_data', models.DateTimeField(auto_now_add=True, verbose_name='评论日期')),
                ('comment_book_name', models.CharField(max_length=50, verbose_name='评论对象')),
            ],
            options={
                'verbose_name_plural': '用户评论',
            },
        ),
        migrations.CreateModel(
            name='MyBooks',
            fields=[
                ('book_master', models.CharField(blank=True, max_length=10, null=True)),
                ('book_name', models.CharField(blank=True, max_length=20, null=True)),
                ('book_num', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': '我的书架',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, verbose_name='用户名')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('is_vip', models.CharField(choices=[('1', '普通用户'), ('2', '会员')], max_length=6, verbose_name='是否是会员')),
            ],
            options={
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='用户昵称')),
                ('gender', models.CharField(choices=[('1', '男'), ('2', '女'), ('3', '保密 ')], max_length=5, verbose_name='性别')),
                ('address', models.CharField(choices=[('1', '安徽'), ('2', '湖南 '), ('3', '上海'), ('4', '北京')], max_length=20, verbose_name='用户地址')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('header_pic', models.ImageField(blank=True, default='head_pic/bird.jpg', null=True, upload_to='head_pic', verbose_name='头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='textApp.User', verbose_name='对应用户')),
            ],
            options={
                'verbose_name_plural': '用户基本信息',
            },
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='books',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='textApp.Books', verbose_name='小说名'),
        ),
    ]
