# Generated by Django 2.0 on 2020-12-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textApp', '0005_auto_20201207_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_end',
            field=models.SmallIntegerField(choices=[(1, '未完结'), (2, '完结')], verbose_name='是否完结'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_type',
            field=models.SmallIntegerField(choices=[(1, '玄幻修真'), (2, '仙侠武侠'), (3, '历史军事'), (4, '科幻游戏'), (5, '悬疑灵幻'), (6, '二次元'), (7, '短篇小说')], verbose_name='小说类型'),
        ),
    ]
