# Generated by Django 2.0.1 on 2020-12-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textApp', '0006_auto_20201207_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, verbose_name='会员名')),
                ('balance', models.IntegerField(default=0)),
                ('create_data', models.DateTimeField()),
                ('expires_data', models.DateTimeField()),
            ],
        ),
    ]
