# Generated by Django 2.0.1 on 2020-12-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textApp', '0007_vipuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipuser',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='vipuser',
            name='create_data',
            field=models.DateTimeField(verbose_name='会员创建时间'),
        ),
        migrations.AlterField(
            model_name='vipuser',
            name='expires_data',
            field=models.DateTimeField(verbose_name='会员到期时间'),
        ),
    ]
