# Generated by Django 2.0.1 on 2020-12-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textApp', '0008_auto_20201209_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vipuser',
            options={'verbose_name_plural': '会员信息'},
        ),
    ]
