# Generated by Django 2.0.1 on 2020-12-09 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textApp', '0009_auto_20201209_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipuser',
            name='user_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='textApp.User', verbose_name='对应用户'),
            preserve_default=False,
        ),
    ]
