# Generated by Django 2.0.1 on 2020-12-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textApp', '0011_auto_20201209_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vipuser',
            name='is_vip',
        ),
        migrations.AddField(
            model_name='user',
            name='is_vip',
            field=models.CharField(choices=[('1', '普通用户'), ('2', '会员')], default='1', max_length=6, verbose_name='是否是会员'),
        ),
    ]
