# Generated by Django 2.0.1 on 2020-12-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textApp', '0012_auto_20201209_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_type',
            field=models.SmallIntegerField(choices=[(1, '玄幻修真'), (2, '仙侠武侠'), (3, '历史军事'), (4, '科幻游戏'), (5, '悬疑灵幻'), (6, '二次元'), (7, '免费')], verbose_name='小说类型'),
        ),
    ]
