# Generated by Django 2.0.1 on 2020-12-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textApp', '0015_auto_20201210_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybooks',
            name='book_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='我的小说图片'),
        ),
    ]
