# Generated by Django 3.1.4 on 2020-12-20 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textApp', '0016_mybooks_book_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_end',
        ),
    ]
