# Generated by Django 3.1.4 on 2020-12-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textApp', '0017_remove_books_book_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_end',
            field=models.SmallIntegerField(choices=[(1, '未完结'), (2, '完结')], default=1, verbose_name='是否完结'),
            preserve_default=False,
        ),
    ]
