# Generated by Django 2.0.1 on 2021-01-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textApp', '0018_books_book_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybooks',
            name='book_img',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='小说图片'),
        ),
    ]
