# Generated by Django 2.0.1 on 2021-01-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textApp', '0019_auto_20210106_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipuser',
            name='user_type',
            field=models.CharField(choices=[(1, '读者'), (2, '作者')], default=1, max_length=10, verbose_name='小说类型'),
            preserve_default=False,
        ),
    ]
