# Generated by Django 2.0.1 on 2021-02-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textApp', '0020_vipuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybooks',
            name='book_author',
            field=models.CharField(default='1', max_length=30, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='mybooks',
            name='book_type',
            field=models.SmallIntegerField(choices=[(1, '玄幻修真'), (2, '仙侠武侠'), (3, '历史军事'), (4, '科幻游戏'), (5, '悬疑灵幻'), (6, '二次元'), (7, '免费')], default='2', verbose_name='小说类型'),
        ),
    ]
